---

    - name: Check commit
      juniper_junos_config:
       provider: "{{ login_junos }}"
       src: "{{folder_network}}/tor1.conf"
       load: override
       diff: yes
#       check_commit_wait: 5
#       confirm: 2
       commit: no
       return_output: yes
       diffs_file: "{{folder_diff}}/build.diff"
       check_commit: yes
      check_mode: yes      
      register: config_results

    - name: print version
      debug:
        var: config_results

